// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tga_decompose_cpp
List tga_decompose_cpp(NumericVector temp, NumericVector mass, int n_components);
RcppExport SEXP _SC25014049_tga_decompose_cpp(SEXP tempSEXP, SEXP massSEXP, SEXP n_componentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mass(massSEXP);
    Rcpp::traits::input_parameter< int >::type n_components(n_componentsSEXP);
    rcpp_result_gen = Rcpp::wrap(tga_decompose_cpp(temp, mass, n_components));
    return rcpp_result_gen;
END_RCPP
}
// baseline_correct_cpp
NumericVector baseline_correct_cpp(NumericVector temperature, NumericVector heat_flow, std::string baseline_method);
RcppExport SEXP _SC25014049_baseline_correct_cpp(SEXP temperatureSEXP, SEXP heat_flowSEXP, SEXP baseline_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type heat_flow(heat_flowSEXP);
    Rcpp::traits::input_parameter< std::string >::type baseline_method(baseline_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(baseline_correct_cpp(temperature, heat_flow, baseline_method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SC25014049_tga_decompose_cpp", (DL_FUNC) &_SC25014049_tga_decompose_cpp, 3},
    {"_SC25014049_baseline_correct_cpp", (DL_FUNC) &_SC25014049_baseline_correct_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SC25014049(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
