# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hirsch-Fye算法单步计算核心函数
#'
#' 这是Hirsch-Fye量子蒙特卡洛算法的核心计算函数，使用C++实现以获得高性能。
#' 该函数计算给定辅助场配置下的传播子和行列式。
#'
#' @param H0 单粒子哈密顿量矩阵
#' @param s 辅助场配置向量，长度为时间切片数L
#' @param U Hubbard相互作用强度
#' @param beta 逆温度
#'
#' @return 包含以下元素的列表：
#'   \item{Bup}{向上自旋的传播子矩阵}
#'   \item{Bdn}{向下自旋的传播子矩阵}
#'   \item{logdet}{对数行列式值，用于Metropolis接受率计算}
#' @examples
#' \dontrun{
#' # 构建哈密顿量
#' H0 <- build_hamiltonian(0, c(-1, 1), c(0.5, 0.5))
#' 
#' # 随机辅助场配置
#' set.seed(123)
#' s <- sample(c(-1, 1), 20, replace = TRUE)
#' 
#' # 运行单步计算
#' result <- hf_step(H0, s, U = 2.0, beta = 5.0)
#' 
#' # 查看结果
#' cat("对数行列式:", result$logdet, "\n")
#' cat("Bup矩阵维度:", dim(result$Bup), "\n")
#' }
#'
#' @export
hf_step <- function(H0, s, U, beta) {
    .Call(`_SC25014049_hf_step`, H0, s, U, beta)
}

