# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tga_decompose_cpp <- function(temp, mass, n_components = 2L) {
    .Call(`_SC25014049_tga_decompose_cpp`, temp, mass, n_components)
}

baseline_correct_cpp <- function(temperature, heat_flow, baseline_method) {
    .Call(`_SC25014049_baseline_correct_cpp`, temperature, heat_flow, baseline_method)
}

