# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_local_minima <- function(x, window = 5L, threshold = 0.1) {
    .Call(`_SC25014049_find_local_minima`, x, window, threshold)
}

baseline_correct_cpp <- function(temperature, heat_flow, baseline_method) {
    .Call(`_SC25014049_baseline_correct_cpp`, temperature, heat_flow, baseline_method)
}

trapezoidal_integral <- function(x, y, start, end) {
    .Call(`_SC25014049_trapezoidal_integral`, x, y, start, end)
}

tga_decompose_cpp <- function(temp, mass, n_components = 2L) {
    .Call(`_SC25014049_tga_decompose_cpp`, temp, mass, n_components)
}

